### ISSUE TITLE
Interfaces not find

### ISSUE THREAD

**Issue by JunfeiYang** [geekwolf/sa-scripts#2]
你好：
   非常感谢你的脚本，但是我在生成环境遇到网络接口没有获取到。请看下面的详细信息：
root@node-8-104:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.130.191.254  0.0.0.0         UG    0      0        0 bond0.1191
10.130.0.0      0.0.0.0         255.255.224.0   U     0      0        0 bond0.1031
10.130.64.0     0.0.0.0         255.255.224.0   U     0      0        0 bond0.1095
10.130.128.0    0.0.0.0         255.255.192.0   U     0      0        0 bond0.1191
10.130.192.0    0.0.0.0         255.255.224.0   U     0      0        0 bond0.1223
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
执行脚本里的变量，没有获取到：
![image](https://user-images.githubusercontent.com/16366286/30960197-e2774a68-a474-11e7-96ee-2b93b032da62.png)
我修改了一些正则表达式，可以获取了。
![image](https://user-images.githubusercontent.com/16366286/30960236-03bc0812-a475-11e7-9f39-ea05ff02bcb8.png)

**Comment by geekwolf** [comment]
@JunfeiYang 可以提交一个commit 修正一下
