### ISSUE TITLE
楼主想问下，你这个脚本，我这边测试无法使用

### ISSUE THREAD

**Issue by jackwhich** [geekwolf/sa-scripts#6]
想请问下，这个脚本，还有其他的东西吗，我看到上面有几个问题
![image](https://user-images.githubusercontent.com/46473862/51450443-c24c5780-1d6b-11e9-94ec-718b96e47c00.png)对python不怎么理解谢谢了

**Comment by geekwolf** [comment]
哪个脚本

**Comment by jackwhich** [comment]
就是zabbix邮件报警附带性能图片的脚本，我对python不是很会，所以想请教下你，你可以加我qq吗，上面说方便点，1028334703，谢谢！我找了好久都没有搞出来
